#certificate of domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificate.secretName  }}
  issuerRef:
    name: {{ .Values.certificate.certresolver }}
    kind: {{ .Values.certificate.certissuerkind  }}
  dnsNames:
    - {{ .Values.ingressroute.host_url }}