{{- if not .Values.secretRef.existingdbsecret }}
#db secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef.dbexistingSecretname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.secretRef.dbexistingSecretkey }}: {{ .Values.secretRef.actualdbpassword | b64enc }}
{{- end }}