{{- if not .Values.secretRef.existingsecret.existingdbsecret }}
#db secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef.secretnametocreate }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.secretRef.existingsecret.dbexistingSecretkey }}: {{ .Values.secretRef.actualdbpassword | b64enc }}
  {{ .Values.secretRef.existingsecret.djangoexistingsecretkeyname }}: {{ .Values.secretRef.actualdjangosecretkey | b64enc }}
{{- end }}
