apiVersion: v1
kind: Service
metadata:
  name: {{ include "staging-locatorapp.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "staging-locatorapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "staging-locatorapp.selectorLabels" . | nindent 4 }}
