# Generated by Django 5.2 on 2025-04-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locappgroups',
            name='LocAppGrp_user',
            field=models.ManyToManyField(related_name='locigroup', to='locator.locappuser'),
        ),
        migrations.AlterField(
            model_name='locapppositions',
            name='LocAppPos_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lociposition', to='locator.locappuser'),
        ),
        migrations.AlterField(
            model_name='locappuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='locappuser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='locappuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='locappuser_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='qrloginsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locator.locappuser'),
        ),
    ]
